/**
 * Helper functions for converting recommendations to calendar events.
 * 
 * Data sources:
 * - recommendations: From PlanContext (generated by generateRecommendations)
 * - plants: From plantsService (to get plant names)
 * - harvestDateIso: From PlanContext (the target harvest date)
 * 
 * This converts the structured recommendation data into flat event objects
 * that can be displayed in a calendar grid.
 */

import type { Plant } from "../../models/Plant";
import type { Recommendation } from "../../reducers/planReducer";

/**
 * Calendar event type representing a single event on a specific date.
 * 
 * Each event represents one action (sow, harden, move, harvest) for one plant
 * on a specific date. Multiple events can occur on the same date.
 */
export type CalendarEvent = {
  type: "sow-outdoor" | "sow-indoor" | "harden-start" | "move-plant-outdoor" | "harvest";
  date: string; // ISO-format (YYYY-MM-DD)
  plantId: number;
  plantName: string;
};

/**
 * Convert recommendations to calendar events.
 * 
 * This function takes the structured recommendation data and converts it
 * into a flat array of events that can be displayed in a calendar grid.
 * 
 * Each recommendation contains multiple dates (sow dates, harden date, etc.),
 * and each date becomes a separate event in the calendar.
 * 
 * Example:
 * - A recommendation with indoorSowDate="2025-03-15" and movePlantOutdoorDate="2025-05-20"
 *   creates two events: one "sow-indoor" on 2025-03-15 and one "move-plant-outdoor" on 2025-05-20
 * 
 * How it works:
 * 1. Creates a map of plantId -> plantName for quick lookup
 * 2. Iterates through each recommendation
 * 3. For each non-null date in the recommendation, creates an event
 * 4. Adds harvest events for each plant using harvestDateIso
 * 5. Returns flat array of all events
 * 
 * @param recommendations - Array of recommendations (one per selected plant)
 * @param plants - Array of all plants (to get plant names by ID)
 * @param harvestDateIso - The target harvest date in ISO format (YYYY-MM-DD) or null
 * 
 * @returns Array of calendar events, one per date and plant combination
 * 
 * @example
 * const recommendations = [
 *   { plantId: 1, indoorSowDate: "2025-03-15", movePlantOutdoorDate: "2025-05-20", ... }
 * ];
 * const plants = [{ id: 1, name: "Tomat" }];
 * const harvestDate = "2025-08-01";
 * const events = recommendationsToEvents(recommendations, plants, harvestDate);
 * // Returns: [
 * //   { type: "sow-indoor", date: "2025-03-15", plantId: 1, plantName: "Tomat" },
 * //   { type: "move-plant-outdoor", date: "2025-05-20", plantId: 1, plantName: "Tomat" },
 * //   { type: "harvest", date: "2025-08-01", plantId: 1, plantName: "Tomat" }
 * // ]
 */
export const recommendationsToEvents = (
  recommendations: Recommendation[],
  plants: Plant[],
  harvestDateIso: string | null
): CalendarEvent[] => {
  const events: CalendarEvent[] = [];

  // Create a map of plantId -> plantName for quick lookup
  const plantMap = new Map<number, string>();
  plants.forEach((plant) => {
    plantMap.set(plant.id, plant.name);
  });

  // Convert each recommendation to events
  recommendations.forEach((recommendation) => {
    const plantName = plantMap.get(recommendation.plantId) ?? "Okänd planta";

    // Outdoor sow date
    if (recommendation.outdoorSowDate) {
      events.push({
        type: "sow-outdoor",
        date: recommendation.outdoorSowDate,
        plantId: recommendation.plantId,
        plantName,
      });
    }

    // Indoor sow date
    if (recommendation.indoorSowDate) {
      events.push({
        type: "sow-indoor",
        date: recommendation.indoorSowDate,
        plantId: recommendation.plantId,
        plantName,
      });
    }

    // Harden start date
    if (recommendation.hardenStartDate) {
      events.push({
        type: "harden-start",
        date: recommendation.hardenStartDate,
        plantId: recommendation.plantId,
        plantName,
      });
    }

    // Move plant outdoor date
    if (recommendation.movePlantOutdoorDate) {
      events.push({
        type: "move-plant-outdoor",
        date: recommendation.movePlantOutdoorDate,
        plantId: recommendation.plantId,
        plantName,
      });
    }

    // Harvest date (one per plant)
    if (harvestDateIso) {
      events.push({
        type: "harvest",
        date: harvestDateIso,
        plantId: recommendation.plantId,
        plantName,
      });
    }
  });

  return events;
};

