/**
 * Helper functions for converting recommendations to calendar events.
 * 
 * Data sources:
 * - recommendations: From PlanContext (generated by generateRecommendations)
 * - plants: From plantsService (to get plant names)
 * - harvestDateIso: From PlanContext (the target harvest date)
 * 
 * This converts the structured recommendation data into flat event objects
 * that can be displayed in a calendar grid.
 */

import type { Plant } from "../../models/Plant";
import type { Recommendation } from "../../reducers/planReducer";

/**
 * Calendar event type representing a single event on a specific date.
 * 
 * Each event represents one action (sow, harden, move, harvest) for one plant
 * on a specific date. Multiple events can occur on the same date.
 */
export type CalendarEventType = "sow-outdoor" | "sow-indoor" | "harden-start" | "move-plant-outdoor" | "harvest";

export type CalendarEvent = {
  type: CalendarEventType;
  date: string; // ISO-format (YYYY-MM-DD)
  plantId: number;
  plantName: string;
  plantSubcategory: string;
};

/**
 * Icon size options for event icons.
 */
export type EventIconSize = "small" | "medium" | "large";

/**
 * Configuration for calendar event types.
 * 
 * Contains labels, tooltip text, and detailed modal content for each event type.
 * Used in CalendarLegend, EventIcon, tooltips, and modals.
 */
export const CALENDAR_EVENT_CONFIG: Record<CalendarEventType, {
  label: string;
  tooltip: string;
  modalTitle: string;
  modalContent: string;
}> = {
  "sow-outdoor": {
    label: "Så direkt ute",
    tooltip: "Så frön direkt i jorden utomhus",
    modalTitle: "Så direkt ute",
    modalContent: "När du sår direkt ute lägger du fröna i jorden där plantorna ska växa. Detta passar för växter som tål kyla och kan hantera utomhusmiljön från början. Vissa växter behöver varmare temperaturer och börjar därför inomhus, medan andra kan sås direkt utomhus när jorden är tillräckligt varm.",
  },
  "sow-indoor": {
    label: "Så inne",
    tooltip: "Så frön inomhus i kruka eller låda",
    modalTitle: "Så inne",
    modalContent: "När du sår inne startar du plantorna i en kontrollerad miljö inomhus. Detta ger plantorna en bättre start och skydd mot kyla och väder. Efter att plantorna har vuxit tillräckligt och väderleken blir varmare, flyttar du ut dem. Detta är vanligt för växter som behöver längre växtid eller är känsliga för kyla.",
  },
  "harden-start": {
    label: "Starta avhärdning",
    tooltip: "Börja vänja plantan vid utomhusmiljön",
    modalTitle: "Starta avhärdning",
    modalContent: "Avhärdning är processen att gradvis vänja plantor som har vuxit inomhus vid utomhusmiljön. Detta görs genom att placera plantorna utomhus i allt längre perioder varje dag, börjande med skugga och skyddade platser. Avhärdning hjälper plantorna att anpassa sig till skillnader i temperatur, vind och solljus, vilket minskar risken för chock och skador när de flyttas ut permanent.",
  },
  "move-plant-outdoor": {
    label: "Flytta ut plantan",
    tooltip: "Flytta plantan från inomhus till utomhus permanent",
    modalTitle: "Flytta ut plantan",
    modalContent: "När plantorna har blivit avhärdade och väderleken är tillräckligt varm, är det dags att flytta ut dem permanent. Detta innebär att plantera dem i sin slutgiltiga plats i trädgården eller i krukor som står utomhus. Se till att jorden är varm nog och att risken för frost är förbi innan du flyttar ut plantorna.",
  },
  "harvest": {
    label: "Skörd",
    tooltip: "Skörda dina växter när de är mogna",
    modalTitle: "Skörd",
    modalContent: "Skörd är när du plockar dina växter när de är mogna och redo att ätas. Olika växter har olika tecken på mognad - vissa ska plockas när de är unga och mjuka, medan andra ska vara fullt utvecklade. Skörda regelbundet för att få bäst smak och för att uppmuntra plantorna att fortsätta producera.",
  },
};

/**
 * Icon size configuration for different contexts.
 * 
 * This allows central control of icon sizes across all components.
 * Change these values to control icon sizes throughout the application.
 */
export const CALENDAR_ICON_SIZES = {
  small: "small" as EventIconSize,
  medium: "medium" as EventIconSize,
  large: "large" as EventIconSize,
} as const;

/**
 * Get all event types in a consistent order.
 */
export const ALL_CALENDAR_EVENT_TYPES: CalendarEventType[] = [
  "sow-outdoor",
  "sow-indoor",
  "harden-start",
  "move-plant-outdoor",
  "harvest",
];

/**
 * Convert recommendations to calendar events.
 * 
 * This function takes the structured recommendation data and converts it
 * into a flat array of events that can be displayed in a calendar grid.
 * 
 * Each recommendation contains multiple dates (sow dates, harden date, etc.),
 * and each date becomes a separate event in the calendar.
 * 
 * Example:
 * - A recommendation with indoorSowDate="2026-03-15" and movePlantOutdoorDate="2026-05-20"
 *   creates two events: one "sow-indoor" on 2026-03-15 and one "move-plant-outdoor" on 2026-05-20
 * 
 * How it works:
 * 1. Creates a map of plantId -> plantName for quick lookup
 * 2. Iterates through each recommendation
 * 3. For each non-null date in the recommendation, creates an event
 * 4. Adds harvest events for each plant using harvestDateIso
 * 5. Returns flat array of all events
 * 
 * @param recommendations - Array of recommendations (one per selected plant)
 * @param plants - Array of all plants (to get plant names by ID)
 * 
 * @returns Array of calendar events, one per date and plant combination
 * 
 * @example
 * const recommendations = [
 *   { plantId: 1, indoorSowDate: "2026-03-15", movePlantOutdoorDate: "2026-05-20", ... }
 * ];
 * const plants = [{ id: 1, name: "Tomat" }];
 * const harvestDate = "2026-08-01";
 * const events = recommendationsToEvents(recommendations, plants, harvestDate);
 * // Returns: [
 * //   { type: "sow-indoor", date: "2026-03-15", plantId: 1, plantName: "Tomat" },
 * //   { type: "move-plant-outdoor", date: "2026-05-20", plantId: 1, plantName: "Tomat" },
 * //   { type: "harvest", date: "2026-08-01", plantId: 1, plantName: "Tomat" }
 * // ]
 */
export const recommendationsToEvents = (
  recommendations: Recommendation[],
  plants: Plant[]
): CalendarEvent[] => {
  const events: CalendarEvent[] = [];

  // Create a map of plantId -> plant for quick lookup
  const plantMap = new Map(plants.map((plant) => [plant.id, plant]));

  // Mapping from recommendation date fields to event types
  const dateFieldToEventType: Array<{
    field: keyof Recommendation;
    type: CalendarEventType;
  }> = [
    { field: "outdoorSowDate", type: "sow-outdoor" },
    { field: "indoorSowDate", type: "sow-indoor" },
    { field: "hardenStartDate", type: "harden-start" },
    { field: "movePlantOutdoorDate", type: "move-plant-outdoor" },
    { field: "harvestDateIso", type: "harvest" },
  ];

  // Convert each recommendation to events
  recommendations.forEach((recommendation) => {
    const plant = plantMap.get(recommendation.plantId);
    const plantName = plant?.name ?? "Okänd planta";
    const plantSubcategory = plant?.subcategory ?? "";

    // Create events for each date field that has a value
    dateFieldToEventType.forEach(({ field, type }) => {
      const date = recommendation[field];
      if (date) {
        events.push({
          type,
          date: date as string,
          plantId: recommendation.plantId,
          plantName,
          plantSubcategory,
        });
      }
    });
  });

  return events;
};

